# Generated by Django 2.2.6 on 2019-11-03 02:58

import cryptographic_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('encrypted_char_field', cryptographic_fields.fields.EncryptedCharField()),
            ],
        ),
    ]
