# Generated by Django 2.2.6 on 2019-11-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='encrypted_char_field',
            new_name='password',
        ),
    ]
