# Generated by Django 2.2.6 on 2019-11-03 04:02

import cryptographic_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsManager', '0002_auto_20191102_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'default_related_name': 'accounts', 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, db_column='x3', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=cryptographic_fields.fields.EncryptedCharField(db_column='x4'),
        ),
        migrations.AlterField(
            model_name='account',
            name='site',
            field=models.CharField(blank=True, db_column='x1', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(blank=True, db_column='x2', max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table='t1',
        ),
    ]
