# Generated by Django 2.2.6 on 2019-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsManager', '0003_auto_20191102_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_account',
            field=models.AutoField(db_column='x0', primary_key=True, serialize=False),
        ),
    ]
