# Generated by Django 2.2.6 on 2019-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsManager', '0004_auto_20191102_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, db_column='x3', max_length=254, null=True),
        ),
    ]
